spring:
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.eft.person.dao
  mapper-locations: classpath:mapper/*.xml

---
spring:
  profiles: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-xb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8081
